Eukleides 1.5.2

diff --git a/bash/euktopdf b/bash/euktopdf
--- a/bash/euktopdf
+++ b/bash/euktopdf
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-#  Eukleides version 1.5.1
+#  Eukleides version 1.5.2
 #  Copyright (c) Christian Obrecht 2004-2010
 #
 #  This program is free software; you can redistribute it and/or modify
@@ -18,7 +18,13 @@
 #  Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 #
 
-src=$(expr $1 : '\(.*\)\.tex' '|' $1)
+if [ ! $1 ]
+then
+    echo "Missing file name. Exiting." > /dev/stderr
+    exit 1
+fi
+
+src=$(expr $1 : '\(.*\)\.[^.]*' '|' $1)
 
 for f in $src-fig*.euk
 do
